// Generated by tools/generate_syscall_signatures.py; do not edit manually.
#pragma once

#include "DirectSyscallDetector/SignaturePrinter.h"

#include <cstddef>
#include <memory>
#include <string_view>

namespace DirectSyscallDetector
{
    [[nodiscard]] std::unique_ptr<const ISyscallSignature> FindGeneratedSyscallSignature(std::string_view functionName);
    [[nodiscard]] std::size_t GeneratedSyscallSignatureCount() noexcept;
}
